### ISSUE TITLE
unocss vscode extenstion 

### ISSUE THREAD

**Issue by moHaHa** [unpreset/unocss-preset-theme#70]
![photo_2023-12-31 03 18 08](https://github.com/unocss/unocss/assets/72744132/f4d7366e-2b01-4841-a486-73f4dc4f6624)

![photo_2023-12-31 03 18 12](https://github.com/unocss/unocss/assets/72744132/d725e228-51db-43d0-8d2c-be13ac7dd717)

**Comment by Dunqing** [comment]
From your screenshot, it looks like you didn't add the color base-light-blue
