### ISSUE TITLE
Color token's opacity value in the light theme gets overwritten by the opacity value of the dark theme

### ISSUE THREAD

**Issue by arfedulov** [unpreset/unocss-preset-theme#75]
**Steps to reproduce**
1. Download the repo https://github.com/arfedulov/reproduce-uno-alpha
2. `npm i`
3. `npm run dev`
4. See that the R, G, B values are correctly applied in light and dark themes for the "my-color-token", but the opacity value in the light theme gets overwritten by the opacity value from the dark theme.

**Comment by arfedulov** [comment]
If this is the bug on the unocss-preset-theme side and it is possible to fix it, I would love to help and make a pull request.

**Comment by Dunqing** [comment]
Thank you for your feedback. Yes, it is a bug on the `unocss-preset-theme`

**Comment by arfedulov** [comment]
Just completed a pull request fixing the issue #76

**Comment by arfedulov** [comment]
@Dunqing May we expect a new npm release soon?

**Comment by Dunqing** [comment]
> @Dunqing May we expect a new npm release soon?

Thanks. I released [v0.13.0](https://github.com/unpreset/unocss-preset-theme/releases/tag/v0.13.0)

**Comment by arfedulov** [comment]
fixed in [v0.13.0](https://github.com/unpreset/unocss-preset-theme/releases/tag/v0.13.0)
